name: Voicey
options:
  bundleIdPrefix: work.voicey
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    PRODUCT_NAME: Voicey
    MARKETING_VERSION: "1.1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    COMBINE_HIDPI_IMAGES: YES
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts.git
    from: "2.0.0"
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    from: "0.9.0"

targets:
  # App Store / TestFlight target
  Voicey:
    type: application
    platform: macOS
    sources:
      - path: Sources/Voicey
        excludes:
          - "**/.DS_Store"
      - path: Resources/Assets.xcassets
        buildPhase: resources
      - path: Resources/AppIcon.icns
        buildPhase: resources
    dependencies:
      - package: KeyboardShortcuts
      - package: WhisperKit
      - sdk: AVFoundation.framework
      - sdk: CoreAudio.framework
      - sdk: Accelerate.framework
      - sdk: Metal.framework
      - sdk: CoreML.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: work.voicey.Voicey
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_ENTITLEMENTS: Voicey.entitlements
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
        ENABLE_APP_SANDBOX: YES
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: ""
    entitlements:
      path: Voicey.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.device.audio-input: true
        com.apple.security.network.client: true

  # Direct distribution target (non-sandboxed, has auto-paste)
  VoiceyDirect:
    type: application
    platform: macOS
    sources:
      - path: Sources/Voicey
        excludes:
          - "**/.DS_Store"
      - path: Resources/Assets.xcassets
        buildPhase: resources
      - path: Resources/AppIcon.icns
        buildPhase: resources
    dependencies:
      - package: KeyboardShortcuts
      - package: WhisperKit
      - sdk: AVFoundation.framework
      - sdk: CoreAudio.framework
      - sdk: Accelerate.framework
      - sdk: Metal.framework
      - sdk: CoreML.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: work.voicey.VoiceyDirect
        PRODUCT_NAME: Voicey
        INFOPLIST_FILE: Info.direct.plist
        CODE_SIGN_ENTITLEMENTS: VoiceyDirect.entitlements
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: VOICEY_DIRECT_DISTRIBUTION
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG VOICEY_DIRECT_DISTRIBUTION
        Release:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: VOICEY_DIRECT_DISTRIBUTION
    entitlements:
      path: VoiceyDirect.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.device.audio-input: true
        com.apple.security.network.client: true

schemes:
  Voicey:
    build:
      targets:
        Voicey: all
    run:
      config: Debug
    archive:
      config: Release

  VoiceyDirect:
    build:
      targets:
        VoiceyDirect: all
    run:
      config: Debug
    archive:
      config: Release
